default_agent: langgraph_bedrock
agents:
  langgraph_bedrock:
    name: langgraph_bedrock
    entrypoint: /Users/youngjik/Documents/GitHub/amazon-bedrock-agentcore-samples/01-tutorials/01-AgentCore-runtime/01-hosting-agent/02-langgraph-with-bedrock-model/langgraph_bedrock.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::720025708473:role/agentcore-langgraph_bedrock-role
      account: '720025708473'
      region: us-west-2
      ecr_repository: 720025708473.dkr.ecr.us-west-2.amazonaws.com/bedrock_agentcore-langgraph_bedrock
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: langgraph_bedrock-4zALE3407c
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:720025708473:runtime/langgraph_bedrock-4zALE3407c
      agent_session_id: a8a3ac46-784b-4f2d-96f8-26d654769400
    authorizer_configuration: null
    oauth_configuration: null
